name: Backend CD (Railway)

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-cd.yml'
  workflow_dispatch:

concurrency:
  group: backend-cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    environment: RECtify (natural-prosperity / production)
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
      RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
    defaults:
      run:
        working-directory: backend
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Validate secrets present
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
        shell: bash
        run: |
          for v in RAILWAY_TOKEN RAILWAY_PROJECT_ID RAILWAY_SERVICE_ID; do
            if [ -z "${!v}" ]; then
              echo "Missing secret: $v"; exit 1;
            fi
          done

      - name: Link project
        run: railway link --project "$RAILWAY_PROJECT_ID" --token "$RAILWAY_TOKEN"

      - name: Link service
        run: railway link --service "$RAILWAY_SERVICE_ID" --token "$RAILWAY_TOKEN"

      - name: Deploy (Nixpacks)
        run: railway up --detach --token "$RAILWAY_TOKEN"

      - name: Show latest deployment
        if: always()
        run: railway deployments --service "$RAILWAY_SERVICE_ID" --limit 1 --token "$RAILWAY_TOKEN" || true