name: Backend CD (Railway)

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-cd.yml'
  workflow_dispatch:

concurrency:
  group: backend-cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    permissions:
      contents: read
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
      RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Link project/service
        run: |
          railway link --project "$RAILWAY_PROJECT_ID" --service "$RAILWAY_SERVICE_ID"

      - name: Deploy (Nixpacks)
        run: |
          railway up --detach

      - name: Show latest deployment
        run: |
          railway deployments --service "$RAILWAY_SERVICE_ID" --limit 1