name: Backend CD (Railway)

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-cd.yml'
  workflow_dispatch:

concurrency:
  group: backend-cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    # CHANGE if your GitHub Environment name is not "production"
    environment: production
    defaults:
      run:
        working-directory: backend
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Auth (browserless via token)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          printf '%s\n' "$RAILWAY_TOKEN" | railway login --browserless
          railway whoami

      - name: Link project
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: railway link --project "$RAILWAY_PROJECT_ID"

      - name: Link service
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
        run: railway link --service "$RAILWAY_SERVICE_ID"

      - name: Deploy (Nixpacks)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --detach

      - name: Show latest deployment
        if: always()
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
        run: railway deployments --service "$RAILWAY_SERVICE_ID" --limit 1 || true