name: Frontend CI

on:
  push:
    paths:
      - 'REC_Website/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    paths:
      - 'REC_Website/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: REC_Website
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: REC_Website/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: rec_website-dist
          path: REC_Website/dist